### ISSUE TITLE
Warning "numpy.ufunc size changed" when importing scipy.optimize

### ISSUE THREAD

**Issue by mhantke** [pytest-dev/pytest-qt#283] opened 2020-01-14 15:55 UTC
During the import of scipy.optimize in my test I am observing a worrisome warning:

RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

If pytest-qt is not installed the warning disappears. Any ideas why this is happening?

---

The test file test_scipy_import.py can be as simple as that:

```python
import scipy.optimize
```

Pip freeze:

```
atomicwrites==1.3.0
attrs==19.3.0
colorama==0.4.3
importlib-metadata==1.4.0
more-itertools==8.1.0
numpy==1.18.1
packaging==20.0
pluggy==0.13.1
py==1.8.1
pyparsing==2.4.6
PySide2==5.14.0
pytest==5.3.2
pytest-qt==3.3.0
scipy==1.4.1
shiboken2==5.14.0
six==1.13.0
wcwidth==0.1.8
zipp==1.0.0

```

Output from: 

```
python -m pytest -W error
=============================================================================== test session starts ===============================================================================
platform win32 -- Python 3.7.5, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
PySide2 5.14.0 -- Qt runtime 5.14.0 -- Qt compiled 5.14.0
rootdir: .
plugins: qt-3.3.0
collected 0 items / 1 error

===================================================================================== ERRORS ======================================================================================
_________________________________________________________________ ERROR collecting testTests/test_scipy_import.py _________________________________________________________________
test_scipy_import.py:5: in <module>
    import scipy.optimize
env_empty\lib\site-packages\scipy\optimize\__init__.py:390: in <module>
    from ._minimize import *
env_empty\lib\site-packages\scipy\optimize\_minimize.py:26: in <module>
    from ._trustregion_dogleg import _minimize_dogleg
env_empty\lib\site-packages\scipy\optimize\_trustregion_dogleg.py:5: in <module>
    import scipy.linalg
env_empty\lib\site-packages\scipy\linalg\__init__.py:196: in <module>
    from .basic import *
env_empty\lib\site-packages\scipy\linalg\basic.py:17: in <module>
    from ._solve_toeplitz import levinson
__init__.pxd:918: in init scipy.linalg._solve_toeplitz
    ???
E   RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================ 1 error in 0.24s =================================================================================
(
```

**Comment by nicoddemus** [comment] 2020-01-14 18:08
Hi @mhantke,

Thanks, I can reproduce the problem.

Seems to be related to `PySide2.QtCore` somehow, because changing your requirements to use `PyQt5` instead the warning disappears.

**Comment by mhantke** [comment] 2020-01-15 09:48
It seems like this has to do with manipulation of warnings.filters. During the import of numpy [a filter is added to silence this warning](https://github.com/numpy/numpy/pull/432/commits/170ed4e33d6196d724dc18ddcd42311c291b4587). This modification of warnings.filters does not succeed if the pytest-qt plugin is installed.

Test file:
```
import warnings
print("warnings.filters:", warnings.filters)
import numpy
print("NUMPY IMPORTED")
print("warnings.filters:", warnings.filters)
import scipy.optimize
```

Outputs:
1) pytest-qt installed
```
python -m pytest -s -W error
================================================================================================================================= test session starts =================================================================================================================================
platform win32 -- Python 3.7.5, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
PySide2 5.14.0 -- Qt runtime 5.14.0 -- Qt compiled 5.14.0
rootdir: .
plugins: qt-3.3.0
collecting ... warnings.filters: [('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
NUMPY IMPORTED
warnings.filters: [('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
collected 0 items / 1 error

======================================================================================================================================= ERRORS ========================================================================================================================================
___________________________________________________________________________________________________________________ ERROR collecting testTests/test_scipy_import.py ___________________________________________________________________________________________________________________
test_scipy_import.py:6: in <module>
    import scipy.optimize
env_empty\lib\site-packages\scipy\optimize\__init__.py:390: in <module>
    from ._minimize import *
env_empty\lib\site-packages\scipy\optimize\_minimize.py:26: in <module>
    from ._trustregion_dogleg import _minimize_dogleg
env_empty\lib\site-packages\scipy\optimize\_trustregion_dogleg.py:5: in <module>
    import scipy.linalg
env_empty\lib\site-packages\scipy\linalg\__init__.py:196: in <module>
    from .basic import *
env_empty\lib\site-packages\scipy\linalg\basic.py:17: in <module>
    from ._solve_toeplitz import levinson
__init__.pxd:918: in init scipy.linalg._solve_toeplitz
    ???
E   RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================================================== 1 error in 0.24s ===================================================================================================================================
```

2) pytest-qt NOT installed
```
python -m pytest -s -W error
================================================================================================================================= test session starts =================================================================================================================================
platform win32 -- Python 3.7.5, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
rootdir: .
collecting ... warnings.filters: [('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
NUMPY IMPORTED
warnings.filters: [('ignore', re.compile('numpy.ndarray size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('ignore', re.compile('numpy.ufunc size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('ignore', re.compile('numpy.dtype size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('always', None, <class 'numpy.RankWarning'>, None, 0), ('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
collected 0 items

================================================================================================================================ no tests ran in 0.60s ================================================================================================================================
```

**Comment by nicoddemus** [comment] 2020-01-15 11:15
What happens if you install `PyQt5` instead of `PySide`?

**Comment by mhantke** [comment] 2020-01-15 11:21
> What happens if you install `PyQt5` instead of `PySide`?

The warning is not raised with `PyQt5`:

```
================================================================================================================================= test session starts =================================================================================================================================
platform win32 -- Python 3.7.5, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
PyQt5 5.14.1 -- Qt runtime 5.14.0 -- Qt compiled 5.14.0
rootdir: .
plugins: qt-3.3.0
collecting ... warnings.filters: [('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
NUMPY IMPORTED
warnings.filters: [('ignore', re.compile('numpy.ndarray size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('ignore', re.compile('numpy.ufunc size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('ignore', re.compile('numpy.dtype size changed', re.IGNORECASE), <class 'Warning'>, None, 0), ('always', None, <class 'numpy.RankWarning'>, None, 0), ('error', None, <class 'Warning'>, None, 0), ('always', None, <class 'PendingDeprecationWarning'>, None, 0), ('always', None, <class 'DeprecationWarning'>, None, 0), ('default', None, <class 'DeprecationWarning'>, '__main__', 0), ('ignore', None, <class 'DeprecationWarning'>, None, 0), ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0), ('ignore', None, <class 'ImportWarning'>, None, 0), ('ignore', None, <class 'ResourceWarning'>, None, 0)]
collected 0 items

================================================================================================================================ no tests ran in 0.60s ================================================================================================================================
```

**Comment by nicoddemus** [comment] 2020-01-15 11:25
That's what I said in https://github.com/pytest-dev/pytest-qt/issues/283#issuecomment-574301801:

> Seems to be related to PySide2.QtCore somehow, because changing your requirements to use PyQt5 instead the warning disappears.

Anyway, looking at the commit message in `numpy` that you posted, I believe it is OK to ignore this warning.

I don't think there's any action to be done on `pytest-qt`'s side, so I'm closing this for now, but feel free to follow with further questions.

**Closed by nicoddemus** 2020-01-15 11:25 UTC
Labels: question :question:
