### ISSUE TITLE
pytest-qt fails when snake_case feature is used in a test

### ISSUE THREAD

**Issue by borco** [pytest-dev/pytest-qt#529] opened 2023-11-22 08:48 UTC
When `snake_case` feature is enabled in a test module, `pytest-qt` fails with:

```
AttributeError: 'PySide6.QtWidgets.QApplication' object has no attribute 'processEvents'. Did you mean: 'process_events'?
```

Here is a minimal test file that produces the error:

```python
from __feature__ import snake_case

def test():
    pass
```

This happens even if you don't use the `qtbot` fixture in the test, as with the example above.

Environment:

python: 3.12.0
pyside6: 6.6.0
pytest-qt: 4.2.0

**Comment by The-Compiler** [comment] 2023-11-22 08:53
Duplicate of #456

**Closed by The-Compiler** 2023-11-22 08:53 UTC
