### ISSUE TITLE
Do clicks on parent widgets get propagated to child widgets?

### ISSUE THREAD

**Issue by mchlnix** [pytest-dev/pytest-qt#286] opened 2020-01-30 20:43 UTC
Hey,

I have a `QMainWindow`, with a `QScrollArea` and a therein a normal `QWidget`.

When I use `qtbot.mouseClick(main_window, ...)` I do not get a reaction in the child widgets. Is this by design, or am I doing something wrong?

(Left out the MVCE, as it's more of a concept question, I hope.)

**Comment by nicoddemus** [comment] 2020-01-30 21:29
Hi @mchlnix, 

That's how Qt works by design, only the widget under the cursor will receive the event.

You will need to install an eventFilter on the widgets, here are some threads on the subject:

* https://forum.qt.io/topic/2992/how-to-catch-all-events-before-reaching-child-widgets-at-a-container-widget/10
* https://forum.qt.io/topic/70594/how-to-handle-keypress-event-for-all-child-widgets-in-qt/2

(Closing for now but feel free to follow with further questions)

**Closed by nicoddemus** 2020-01-30 21:29 UTC
